---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Devops_Project-app
  labels:
    app: Devops_Project-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Devops_Project-app
  template:
    metadata:
      labels:
        app: Devops_Project-app
    spec:
      containers:
      - name: Devops_Project-container
        image: 598537770925.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
